CREATE TABLE "categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar(100) NOT NULL,
  "parent_category_id" int,
  "category_path" varchar(500),
  "description" text,
  "display_order" int DEFAULT 0,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "clothing_types" (
  "type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_name" varchar(50) UNIQUE NOT NULL,
  "category_id" int,
  "display_order" int DEFAULT 0,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "sizes" (
  "size_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "size_name" varchar(20) NOT NULL,
  "size_category" varchar(20),
  "size_group" varchar(20) DEFAULT 'Standard',
  "sort_order" int DEFAULT 0,
  "measurements" json,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "colors" (
  "color_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "color_name" varchar(50) NOT NULL,
  "color_code" varchar(10),
  "color_family" varchar(30),
  "is_active" boolean DEFAULT true
);

CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" varchar(255) NOT NULL,
  "product_code" varchar(50) UNIQUE NOT NULL,
  "slug" varchar(255) UNIQUE NOT NULL,
  "description" text,
  "short_description" text,
  "category_id" int,
  "clothing_type_id" int,
  "season" varchar(50),
  "gender" varchar(20),
  "base_price" decimal(10,2) NOT NULL,
  "sale_price" decimal(10,2),
  "cost_price" decimal(10,2),
  "is_featured" boolean DEFAULT false,
  "is_new_arrival" boolean DEFAULT false,
  "is_bestseller" boolean DEFAULT false,
  "status" varchar(20) DEFAULT 'Active',
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "product_variants" (
  "variant_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "sku" varchar(100) UNIQUE NOT NULL,
  "size_id" int,
  "color_id" int,
  "price" decimal(10,2) NOT NULL,
  "sale_price" decimal(10,2),
  "weight" decimal(8,3),
  "dimensions" varchar(100),
  "barcode" varchar(50),
  "stock_quantity" int DEFAULT 0,
  "low_stock_threshold" int DEFAULT 5,
  "status" varchar(20) DEFAULT 'Active',
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "first_name" varchar(100),
  "last_name" varchar(100),
  "phone" varchar(20),
  "role" varchar(20) DEFAULT 'customer',
  "is_active" boolean DEFAULT true,
  "email_verified" boolean DEFAULT false,
  "email_verified_at" timestamp,
  "last_login" timestamp,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "user_addresses" (
  "address_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "address_type" varchar(20) DEFAULT 'Both',
  "first_name" varchar(100),
  "last_name" varchar(100),
  "address_line1" varchar(255) NOT NULL,
  "address_line2" varchar(255),
  "city" varchar(100) NOT NULL,
  "region" varchar(100),
  "country" varchar(100) NOT NULL DEFAULT 'Kyrgyzstan',
  "postal_code" varchar(20) NOT NULL,
  "phone" varchar(20),
  "is_default" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "shopping_cart" (
  "cart_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "session_id" varchar(255),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "cart_items" (
  "cart_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" int NOT NULL,
  "variant_id" int NOT NULL,
  "quantity" int NOT NULL DEFAULT 1,
  "price" decimal(10,2) NOT NULL,
  "added_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "wishlists" (
  "wishlist_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "product_id" int NOT NULL,
  "added_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_number" varchar(50) UNIQUE NOT NULL,
  "user_id" int,
  "guest_email" varchar(255),
  "order_date" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "order_status" varchar(20) DEFAULT 'Pending',
  "payment_status" varchar(20) DEFAULT 'Pending',
  "payment_method" varchar(50),
  "payment_transaction_id" varchar(100),
  "shipping_address_id" int,
  "billing_address_id" int,
  "shipping_method" varchar(50),
  "delivery_date" date,
  "tracking_number" varchar(100),
  "fx_rate_to_base" decimal(18,8),
  "fx_source" varchar(50),
  "subtotal_base" decimal(12,2),
  "shipping_cost_base" decimal(12,2),
  "discount_base" decimal(12,2),
  "total_amount_base" decimal(12,2),
  "currency_id" int NOT NULL,
  "notes" text,
  "admin_notes" text
);

CREATE TABLE "currencies" (
  "currency_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "currency_code" varchar(3) UNIQUE NOT NULL,
  "currency_name" varchar(50) NOT NULL,
  "currency_symbol" varchar(5),
  "exchange_rate" decimal(12,6) NOT NULL DEFAULT 1,
  "is_base_currency" boolean DEFAULT false,
  "is_active" boolean DEFAULT true,
  "decimal_places" int DEFAULT 2,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "order_items" (
  "order_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "variant_id" int NOT NULL,
  "product_name" varchar(255),
  "variant_details" varchar(255),
  "quantity" int NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "discount_amount" decimal(10,2) DEFAULT 0,
  "total_price" decimal(10,2) NOT NULL
);

CREATE TABLE "payments" (
  "payment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "payment_method" varchar(50) NOT NULL,
  "payment_provider" varchar(50),
  "transaction_id" varchar(100),
  "amount" decimal(10,2) NOT NULL,
  "currency_id" int NOT NULL,
  "status" varchar(20),
  "gateway_response" json,
  "processed_at" timestamp,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "fx_rates" (
  "fx_rate_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "base_currency_id" int NOT NULL,
  "quote_currency_id" int NOT NULL,
  "rate" decimal(18,8) NOT NULL,
  "source" varchar(50) DEFAULT 'manual',
  "as_of" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "delivery_zones" (
  "zone_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zone_name" varchar(100) NOT NULL,
  "cities" text,
  "delivery_cost" decimal(10,2) NOT NULL,
  "delivery_time_days" int DEFAULT 3,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "product_images" (
  "image_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "variant_id" int,
  "image_url" varchar(500) NOT NULL,
  "alt_text" varchar(255),
  "is_primary" boolean DEFAULT false,
  "display_order" int DEFAULT 0,
  "image_type" varchar(20) DEFAULT 'Gallery',
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "collections" (
  "collection_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "collection_name" varchar(100) NOT NULL,
  "collection_slug" varchar(255) UNIQUE NOT NULL,
  "description" text,
  "banner_image" varchar(500),
  "is_featured" boolean DEFAULT false,
  "display_order" int DEFAULT 0,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "collection_products" (
  "collection_id" int,
  "product_id" int,
  "display_order" int DEFAULT 0,
  PRIMARY KEY ("collection_id", "product_id")
);

CREATE TABLE "related_products" (
  "relation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "related_product_id" int NOT NULL,
  "relation_type" varchar(20) DEFAULT 'related',
  "display_order" int DEFAULT 0,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "product_views" (
  "view_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "user_id" int,
  "session_id" varchar(255),
  "ip_address" varchar(45),
  "viewed_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "admin_logs" (
  "log_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_id" int,
  "action" varchar(100),
  "table_name" varchar(50),
  "record_id" int,
  "old_values" json,
  "new_values" json,
  "ip_address" varchar(45),
  "user_agent" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE UNIQUE INDEX "unique_user_product_wishlist" ON "wishlists" ("user_id", "product_id");

CREATE INDEX "idx_fx_pair_time" ON "fx_rates" ("base_currency_id", "quote_currency_id", "as_of");

CREATE INDEX "idx_product_relations" ON "related_products" ("product_id", "relation_type");

CREATE INDEX "idx_related_product" ON "related_products" ("related_product_id");

CREATE INDEX "idx_product_views" ON "product_views" ("product_id", "viewed_at");

CREATE INDEX "idx_user_views" ON "product_views" ("user_id", "viewed_at");

COMMENT ON TABLE "categories" IS 'Hierarchical: Clothing > Shirts > T-Shirts';

COMMENT ON TABLE "clothing_types" IS 'Shirt, T-Shirt, Pants, Jeans, Dress, etc.';

COMMENT ON COLUMN "sizes"."size_category" IS 'Clothing, Shoes, Accessories';

COMMENT ON COLUMN "sizes"."size_group" IS 'XS, S, M, L, XL or 28, 30, 32';

COMMENT ON COLUMN "sizes"."measurements" IS 'chest, waist, hip measurements';

COMMENT ON COLUMN "colors"."color_code" IS 'Hex color code #FF0000';

COMMENT ON COLUMN "colors"."color_family" IS 'Red, Blue, Green, etc.';

COMMENT ON COLUMN "products"."slug" IS 'URL-friendly: blue-cotton-tshirt';

COMMENT ON COLUMN "products"."short_description" IS 'For product cards';

COMMENT ON COLUMN "products"."season" IS 'Spring, Summer, Fall, Winter';

COMMENT ON COLUMN "products"."gender" IS 'Men, Women, Unisex, Kids';

COMMENT ON COLUMN "products"."sale_price" IS 'Discounted price if on sale';

COMMENT ON COLUMN "products"."is_featured" IS 'Show on homepage';

COMMENT ON COLUMN "products"."status" IS 'Active, Inactive, Draft';

COMMENT ON COLUMN "product_variants"."weight" IS 'For shipping calculations';

COMMENT ON COLUMN "product_variants"."stock_quantity" IS 'Current stock level';

COMMENT ON COLUMN "product_variants"."status" IS 'Active, Inactive, Out of Stock';

COMMENT ON COLUMN "users"."role" IS 'admin, manager, customer';

COMMENT ON COLUMN "user_addresses"."address_type" IS 'Billing, Shipping, Both';

COMMENT ON COLUMN "shopping_cart"."session_id" IS 'For guest users';

COMMENT ON COLUMN "cart_items"."price" IS 'Price when added to cart';

COMMENT ON COLUMN "orders"."guest_email" IS 'For guest checkout';

COMMENT ON COLUMN "orders"."order_status" IS 'Pending, Confirmed, Processing, Shipped, Delivered, Cancelled, Returned';

COMMENT ON COLUMN "orders"."payment_status" IS 'Pending, Paid, Failed, Refunded, Partially Refunded';

COMMENT ON COLUMN "orders"."payment_method" IS 'FreedomPay KG, Cash on Delivery';

COMMENT ON COLUMN "orders"."shipping_method" IS 'Standard, Express, Same Day';

COMMENT ON COLUMN "orders"."fx_rate_to_base" IS 'quote->base at purchase time';

COMMENT ON COLUMN "orders"."currency_id" IS 'Order currency';

COMMENT ON COLUMN "orders"."admin_notes" IS 'Internal notes for managers';

COMMENT ON TABLE "currencies" IS 'Base currency (KGS), others calculated via exchange rate';

COMMENT ON COLUMN "currencies"."currency_code" IS 'KGS, USD, EUR, RUB';

COMMENT ON COLUMN "currencies"."currency_name" IS 'Kyrgyz Som, US Dollar';

COMMENT ON COLUMN "currencies"."currency_symbol" IS 'с, $, €, ₽';

COMMENT ON COLUMN "currencies"."exchange_rate" IS 'Rate to base currency';

COMMENT ON COLUMN "currencies"."is_base_currency" IS 'Only one base currency';

COMMENT ON COLUMN "currencies"."decimal_places" IS 'Number of decimal places';

COMMENT ON COLUMN "order_items"."product_name" IS 'Snapshot at time of order';

COMMENT ON COLUMN "order_items"."variant_details" IS 'Size, Color details snapshot';

COMMENT ON COLUMN "payments"."payment_provider" IS 'FreedomPay KG';

COMMENT ON COLUMN "payments"."status" IS 'Pending, Completed, Failed, Refunded';

COMMENT ON COLUMN "payments"."gateway_response" IS 'Store payment gateway response';

COMMENT ON TABLE "delivery_zones" IS 'Bishkek - 200 KGS (1-2 days), Regions - 300 KGS (3-5 days)';

COMMENT ON COLUMN "delivery_zones"."cities" IS 'Comma-separated city names';

COMMENT ON COLUMN "product_images"."image_type" IS 'Main, Gallery, Thumbnail, Hover';

COMMENT ON TABLE "related_products" IS 'For "See Also", "You might also like", "Similar Products"';

COMMENT ON COLUMN "related_products"."relation_type" IS 'related, similar, upsell, crosssell';

COMMENT ON TABLE "product_views" IS 'Track product views for analytics and recommendations';

COMMENT ON COLUMN "product_views"."session_id" IS 'For guest users';

COMMENT ON COLUMN "admin_logs"."action" IS 'CREATE_PRODUCT, UPDATE_ORDER, DELETE_USER';

ALTER TABLE "clothing_types" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "products" ADD FOREIGN KEY ("clothing_type_id") REFERENCES "clothing_types" ("type_id");

ALTER TABLE "product_variants" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "product_variants" ADD FOREIGN KEY ("size_id") REFERENCES "sizes" ("size_id");

ALTER TABLE "product_variants" ADD FOREIGN KEY ("color_id") REFERENCES "colors" ("color_id");

ALTER TABLE "user_addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "shopping_cart" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "shopping_cart" ("cart_id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("variant_id");

ALTER TABLE "wishlists" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "wishlists" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("shipping_address_id") REFERENCES "user_addresses" ("address_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("billing_address_id") REFERENCES "user_addresses" ("address_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("currency_id") REFERENCES "currencies" ("currency_id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("variant_id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "payments" ADD FOREIGN KEY ("currency_id") REFERENCES "currencies" ("currency_id");

ALTER TABLE "fx_rates" ADD FOREIGN KEY ("base_currency_id") REFERENCES "currencies" ("currency_id");

ALTER TABLE "fx_rates" ADD FOREIGN KEY ("quote_currency_id") REFERENCES "currencies" ("currency_id");

ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "product_images" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("variant_id");

ALTER TABLE "collection_products" ADD FOREIGN KEY ("collection_id") REFERENCES "collections" ("collection_id");

ALTER TABLE "collection_products" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "related_products" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "related_products" ADD FOREIGN KEY ("related_product_id") REFERENCES "products" ("product_id");

ALTER TABLE "product_views" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "product_views" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "admin_logs" ADD FOREIGN KEY ("admin_id") REFERENCES "users" ("user_id");

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "fx_rates" ADD FOREIGN KEY ("base_currency_id") REFERENCES "fx_rates" ("fx_rate_id");
