# Generated by Django 5.0.6 on 2025-09-24 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_in', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'wishlists',
                'indexes': [models.Index(fields=['user'], name='wishlists_user_id_69623b_idx'), models.Index(fields=['session_id'], name='wishlists_session_e0afd1_idx'), models.Index(fields=['variant'], name='wishlists_variant_e68484_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='wishlists',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('session_id__isnull', False), _connector='OR'), name='wishlist_has_user_or_session'),
        ),
        migrations.AddConstraint(
            model_name='wishlists',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'variant'), name='uniq_user_variant_wishlist'),
        ),
        migrations.AddConstraint(
            model_name='wishlists',
            constraint=models.UniqueConstraint(condition=models.Q(('session_id__isnull', False)), fields=('session_id', 'variant'), name='uniq_session_variant_wishlist'),
        ),
    ]
