# Generated by Django 5.0.6 on 2025-08-28 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_in', to='catalog.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='wishlist_wi_user_id_624270_idx'), models.Index(fields=['session_id'], name='wishlist_wi_session_91b682_idx'), models.Index(fields=['variant'], name='wishlist_wi_variant_c3c474_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='wishlists',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('session_id__isnull', False), _connector='OR'), name='wishlist_has_user_or_session'),
        ),
        migrations.AddConstraint(
            model_name='wishlists',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'variant'), name='uniq_user_variant'),
        ),
        migrations.AddConstraint(
            model_name='wishlists',
            constraint=models.UniqueConstraint(condition=models.Q(('session_id__isnull', False)), fields=('session_id', 'variant'), name='uniq_session_variant'),
        ),
    ]
