# Generated by Django 5.0.6 on 2025-09-24 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_code', models.CharField(db_comment='KGS, USD, EUR, RUB', max_length=3, unique=True)),
                ('currency_name', models.CharField(db_comment='Kyrgyz Som, US Dollar', max_length=50)),
                ('currency_symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('exchange_rate', models.DecimalField(db_comment='Rate to base currency', decimal_places=6, max_digits=12)),
                ('is_base_currency', models.BooleanField(blank=True, db_comment='Only one base currency', null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('decimal_places', models.IntegerField(blank=True, db_comment='Number of decimal places', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currencies',
                'db_table_comment': 'Base currency (KGS), others calculated via exchange rate',
            },
        ),
        migrations.CreateModel(
            name='AdminLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, db_comment='CREATE_PRODUCT, UPDATE_ORDER, DELETE_USER', max_length=100, null=True)),
                ('table_name', models.CharField(blank=True, max_length=50, null=True)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('old_values', models.TextField(blank=True, null=True)),
                ('new_values', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_logs',
            },
        ),
        migrations.CreateModel(
            name='ProductViews',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_comment='For guest users', max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_views',
                'db_table_comment': 'Track product views for analytics and recommendations',
            },
        ),
    ]
