# Generated by Django 5.0.6 on 2025-09-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_adminlogs_created_at_alter_currency_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Валюты'},
        ),
    ]
