# Generated by Django 5.0.6 on 2025-08-28 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_provider', models.CharField(blank=True, help_text='FreedomPay KG', max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('fx_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(blank=True, default='manual', max_length=50)),
                ('as_of', models.DateTimeField(auto_now_add=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_base_rates', to='core.currency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_quote_rates', to='core.currency')),
            ],
            options={
                'db_table': 'fx_rates',
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', 'as_of'], name='idx_fx_pair_time')],
            },
        ),
    ]
