# Generated by Django 5.0.6 on 2025-10-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_options_alter_useraddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'клиент'), ('manager', 'менеджер'), ('admin', 'админ')], default='customer', max_length=20, verbose_name='Роль'),
        ),
    ]
