# Generated by Django 5.0.6 on 2025-10-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='last_name',
        ),
    ]
