# Generated by Django 5.0.6 on 2025-12-03 08:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_banners', wagtail.fields.StreamField([('hero_banner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Banner image (recommended size: 1920x800px)', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Banner title', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Banner description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Button text (e.g., 'Перейти', 'Узнать больше')", 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': "Button link (e.g., '/collections/evening')", 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('cta_text', 3), ('cta_link', 4)]], {})}, help_text='Add multiple banners to create a carousel')),
                ('collection_tiles', wagtail.fields.StreamField([('collection_tile', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Tile image (recommended size: 600x800px)', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Tile title', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Tile description', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': "Collection link (e.g., '/collections/spring-2025')", 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('link', 3)]], {})}, help_text='Add 4 collection tiles for the grid')),
                ('collection_banner', wagtail.fields.StreamField([('collection_banner', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Banner title (supports line breaks with \\n)', 'max_length': 200, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Banner description', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': "Button link (e.g., '/collections/spring-2025')", 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('cta_text', 2), ('cta_link', 3)]], {})}, help_text='Add one collection banner')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('twitter', 'Twitter / X'), ('other', 'Other')], help_text='Social media platform', max_length=20)),
                ('url', models.URLField(help_text='Full URL (e.g., https://instagram.com/nelylook)')),
                ('display_order', models.IntegerField(default=0, help_text='Order in footer (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this link in footer')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['display_order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Section heading', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Paragraph text with formatting', 'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Add an image', 'icon': 'image'})}, help_text='Build your page content with these blocks')),
            ],
            options={
                'verbose_name': 'Text Page',
                'verbose_name_plural': 'Text Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CollectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, help_text='Hero title (leave blank to use page title)', max_length=200)),
                ('hero_description', wagtail.fields.RichTextField(blank=True, help_text='Hero description text')),
                ('collection_slug', models.CharField(blank=True, help_text="Collection identifier (e.g., 'spring-2025', 'evening', 'everyday'). Must match your Django collection slug.", max_length=100)),
                ('hero_image', models.ForeignKey(blank=True, help_text='Collection hero image (recommended size: 1920x600px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Collection Page',
                'verbose_name_plural': 'Collection Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
