# Generated by Django 5.0.6 on 2025-12-06 11:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='collection_banner',
            field=wagtail.fields.StreamField([('collection_banner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Banner background image (recommended size: 1920x600px)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Banner title (supports line breaks with \\n)', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Banner description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text', 'max_length': 50, 'required': False}), 4: ('apps.cms_content.models.RelativeURLBlock', (), {'help_text': "Button link (e.g., '/collections/spring-2025' or 'https://example.com')", 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('cta_text', 3), ('cta_link', 4)]], {})}, help_text='Add one collection banner'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='collection_tiles',
            field=wagtail.fields.StreamField([('collection_tile', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Tile image (recommended size: 600x800px)', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Tile title', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Tile description', 'required': False}), 3: ('apps.cms_content.models.RelativeURLBlock', (), {'help_text': "Collection link (e.g., '/collections/spring-2025' or 'https://example.com')", 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('link', 3)]], {})}, help_text='Add 4 collection tiles for the grid'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_banners',
            field=wagtail.fields.StreamField([('hero_banner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Banner image (recommended size: 1920x800px)', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Banner title', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Banner description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Button text (e.g., 'Перейти', 'Узнать больше')", 'max_length': 50, 'required': False}), 4: ('apps.cms_content.models.RelativeURLBlock', (), {'help_text': "Button link (e.g., '/collections/evening' or 'https://example.com')", 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('cta_text', 3), ('cta_link', 4)]], {})}, help_text='Add multiple banners to create a carousel'),
        ),
    ]
