# Generated by Django 5.0.6 on 2025-12-06 11:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0002_alter_homepage_collection_banner_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text')),
                ('body', wagtail.fields.StreamField([('text_block', 2), ('image', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading', 'max_length': 200, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Text content with formatting', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Add an image', 'icon': 'image'})}, help_text='Page content')),
            ],
            options={
                'verbose_name': 'About Us Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text')),
                ('contact_info', wagtail.fields.StreamField([('contact_block', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Section title (e.g., 'Телефон', 'Email')", 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Contact details', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Icon name (optional)', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1), ('icon', 2)]], {})}, help_text='Contact information blocks')),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text')),
                ('faqs', wagtail.fields.StreamField([('faq_item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Question', 'max_length': 500, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Answer', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}, help_text='Add FAQ items')),
            ],
            options={
                'verbose_name': 'FAQ Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('text_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading', 'max_length': 200, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Text content with formatting', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 1)]], {})}, help_text='Privacy policy content')),
            ],
            options={
                'verbose_name': 'Privacy Policy Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ReturnsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('text_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading', 'max_length': 200, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Text content with formatting', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 1)]], {})}, help_text='Returns and exchanges policy content')),
            ],
            options={
                'verbose_name': 'Returns & Exchanges Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('text_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading', 'max_length': 200, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Text content with formatting', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 1)]], {})}, help_text='Terms of service content')),
            ],
            options={
                'verbose_name': 'Terms of Service Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('text_block', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Section heading', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Paragraph text with formatting', 'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Add an image', 'icon': 'image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading', 'max_length': 200, 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Text content with formatting', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('heading', 3), ('content', 4)]], {})}, help_text='Build your page content with these blocks'),
        ),
    ]
