# Generated by Django 5.0.6 on 2025-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0003_add_content_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, help_text='Например: ул. Токтогула 123', max_length=255, verbose_name='Адрес строка 1')),
                ('address_line2', models.CharField(blank=True, help_text='Например: Бишкек, Кыргызстан', max_length=255, verbose_name='Адрес строка 2')),
                ('phone1', models.CharField(blank=True, help_text='Например: +996 708 200 125', max_length=50, verbose_name='Телефон 1')),
                ('phone2', models.CharField(blank=True, help_text='Например: +996 708 268 626', max_length=50, verbose_name='Телефон 2')),
                ('email1', models.EmailField(blank=True, help_text='Например: info@nelylook.com', max_length=254, verbose_name='Email 1')),
                ('email2', models.EmailField(blank=True, help_text='Например: support@nelylook.com', max_length=254, verbose_name='Email 2')),
                ('working_hours_weekday', models.CharField(blank=True, help_text='Например: 10:00 - 20:00', max_length=100, verbose_name='Часы работы (Пн-Пт)')),
                ('working_hours_weekend', models.CharField(blank=True, help_text='Например: 10:00 - 18:00', max_length=100, verbose_name='Часы работы (Сб-Вс)')),
                ('whatsapp_url', models.URLField(blank=True, help_text='Например: https://wa.me/996708200125', verbose_name='WhatsApp')),
                ('telegram_url', models.URLField(blank=True, help_text='Например: https://t.me/nelylook', verbose_name='Telegram')),
                ('instagram_url', models.URLField(blank=True, help_text='Например: https://instagram.com/nelylook', verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
