# Generated by Django 5.0.6 on 2025-12-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0004_add_contact_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='telegram_url',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='whatsapp_url',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='working_hours_weekday',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='working_hours_weekend',
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='contact_text',
            field=models.TextField(blank=True, help_text='Введите всю контактную информацию здесь. Используйте новые строки для разделения.', verbose_name='Контактная информация'),
        ),
    ]
