# Generated by Django 5.0.6 on 2025-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0005_simplify_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='contact_text',
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='address',
            field=models.TextField(blank=True, help_text='Введите адрес. Можно использовать несколько строк.', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='emails',
            field=models.TextField(blank=True, help_text='Введите email адреса. Можно использовать несколько строк.', verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='phones',
            field=models.TextField(blank=True, help_text='Введите номера телефонов. Можно использовать несколько строк.', verbose_name='Телефоны'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='social_links',
            field=models.TextField(blank=True, help_text='Введите ссылки на социальные сети (WhatsApp, Telegram, Instagram). Можно использовать несколько строк.', verbose_name='Социальные сети'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='working_hours',
            field=models.TextField(blank=True, help_text='Введите часы работы. Можно использовать несколько строк.', verbose_name='Время работы'),
        ),
    ]
