# Generated by Django 5.0.6 on 2025-12-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0006_contact_info_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='social_links',
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Например: https://instagram.com/nelylook', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='Например: https://t.me/nelylook', verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='Например: https://wa.me/996708200125', verbose_name='WhatsApp'),
        ),
    ]
