# Generated by Django 5.0.6 on 2025-12-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0007_add_social_media_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Например: https://instagram.com/nely.look', verbose_name='Instagram'),
        ),
        migrations.DeleteModel(
            name='CollectionPage',
        ),
    ]
