# Generated by Django 5.0.6 on 2025-12-10 07:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0008_remove_collection_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicypage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Privacy policy content - use the rich text editor to format headings, lists, etc.'),
        ),
    ]
