# Generated by Django 5.0.6 on 2025-12-10 08:22

import wagtail.fields
from django.db import migrations


def clear_privacy_policy_body(apps, schema_editor):
    """Clear body field to allow field type change"""
    PrivacyPolicyPage = apps.get_model('cms_content', 'PrivacyPolicyPage')
    PrivacyPolicyPage.objects.all().update(body='[]')


class Migration(migrations.Migration):

    dependencies = [
        ('cms_content', '0009_alter_privacypolicypage_body'),
    ]

    operations = [
        # First, clear the body field data
        migrations.RunPython(clear_privacy_policy_body, migrations.RunPython.noop),
        # Then alter the field type
        migrations.AlterField(
            model_name='privacypolicypage',
            name='body',
            field=wagtail.fields.StreamField([('text_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading', 'max_length': 200, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Text content with formatting', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 1)]], {})}, help_text='Privacy policy content'),
        ),
    ]
