# Generated by Django 5.0.6 on 2025-08-27 11:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_comment='For guest users', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopping_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(db_comment='Price when added to cart', decimal_places=2, max_digits=10)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productvariant')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.shoppingcart')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['user', 'session_id'], name='shopping_ca_user_id_81f451_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitems',
            constraint=models.UniqueConstraint(fields=('cart', 'variant'), name='uniq_cart_variant'),
        ),
    ]
