# Generated by Django 5.0.6 on 2025-08-28 09:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZones',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100, unique=True)),
                ('cities', models.TextField(blank=True, help_text='Comma-separated city names', null=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery zone',
                'verbose_name_plural': 'Delivery zones',
                'db_table': 'delivery_zones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('guest_email', models.EmailField(blank=True, help_text='For guest checkout', max_length=254, null=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_status', models.CharField(blank=True, help_text='Pending, Confirmed, Processing, Shipped, Delivered, Cancelled, Returned', max_length=20, null=True)),
                ('payment_status', models.CharField(blank=True, help_text='Pending, Paid, Failed, Refunded, Partially Refunded', max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='FreedomPay KG, Cash on Delivery', max_length=50, null=True)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('fx_rate_to_base', models.DecimalField(blank=True, decimal_places=8, help_text='quote->base at purchase time', max_digits=18, null=True)),
                ('fx_source', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_cost_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for managers', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to='authentication.useraddress')),
                ('currency', models.ForeignKey(help_text='Order currency', on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='authentication.useraddress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, help_text='Snapshot at time of order', max_length=255, null=True)),
                ('variant_details', models.CharField(blank=True, help_text='Size, Color details snapshot', max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='orders_orde_user_id_a87c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='orders_orde_order_d_d71205_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='orders_orde_order_s_33197f_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('guest_email__isnull', False), _connector='OR'), name='order_has_user_or_guest_email'),
        ),
        migrations.AddIndex(
            model_name='orderitems',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d6920_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitems',
            index=models.Index(fields=['variant'], name='orders_orde_variant_be4097_idx'),
        ),
    ]
