# Generated by Django 5.0.6 on 2025-08-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=100)),
                ('collection_slug', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_featured', models.BooleanField(blank=True, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(blank=True, db_comment='Hex color code #FF0000', max_length=10, null=True)),
                ('color_family', models.CharField(blank=True, db_comment='Red, Blue, Green, etc.', max_length=30, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=20)),
                ('size_category', models.CharField(blank=True, db_comment='Clothing, Shoes, Accessories', max_length=20, null=True)),
                ('size_group', models.CharField(blank=True, db_comment='XS, S, M, L, XL or 28, 30, 32', max_length=20, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('measurements', models.TextField(blank=True, db_comment='chest, waist, hip measurements', null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_path', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'db_table': 'categories',
                'db_table_comment': 'Hierarchical: Clothing > Shirts > T-Shirts',
            },
        ),
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
            options={
                'db_table': 'clothing_types',
                'db_table_comment': 'Shirt, T-Shirt, Pants, Jeans, Dress, etc.',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(db_comment='URL-friendly: blue-cotton-tshirt', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, db_comment='For product cards', null=True)),
                ('season', models.CharField(blank=True, db_comment='Spring, Summer, Fall, Winter', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_comment='Men, Women, Unisex, Kids', max_length=20, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, db_comment='Discounted price if on sale', decimal_places=2, max_digits=10, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_featured', models.BooleanField(blank=True, db_comment='Show on homepage', null=True)),
                ('is_new_arrival', models.BooleanField(blank=True, null=True)),
                ('is_bestseller', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_comment='Active, Inactive, Draft', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
                ('clothing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.clothingtype')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='CollectionProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_products', to='catalog.collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to='catalog.product')),
            ],
            options={
                'db_table': 'collection_products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, db_comment='For shipping calculations', decimal_places=3, max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, db_comment='Current stock level', null=True)),
                ('low_stock_threshold', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_comment='Active, Inactive, Out of Stock', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.size')),
            ],
            options={
                'db_table': 'product_variants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(blank=True, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('image_type', models.CharField(blank=True, db_comment='Main, Gallery, Thumbnail, Hover', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(blank=True, db_comment='related, similar, upsell, crosssell', max_length=20, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedproducts_related_product_set', to='catalog.product')),
            ],
            options={
                'db_table': 'related_products',
                'db_table_comment': 'For "See Also", "You might also like", "Similar Products"',
            },
        ),
        migrations.AddConstraint(
            model_name='collectionproduct',
            constraint=models.UniqueConstraint(fields=('collection', 'product'), name='uniq_collection_product'),
        ),
    ]
