# Generated by Django 5.0.6 on 2025-09-30 10:42

import apps.core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='clothingtype',
            options={'verbose_name_plural': 'Тип одежды'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='collectionproduct',
            options={'verbose_name_plural': 'Коллекционные товары'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order'], 'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'color', 'size'], 'verbose_name_plural': 'Вариации товаров'},
        ),
        migrations.AlterModelOptions(
            name='relatedproduct',
            options={'verbose_name_plural': 'Похожие товары'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['sort_order', 'size_name'], 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Загрузите фото (будет сохранено в Supabase)', null=True, storage=apps.core.storage.SupabaseStorage, upload_to='products/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='Главная категория'),
        ),
        migrations.AlterField(
            model_name='clothingtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_types', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='clothingtype',
            name='display_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='clothingtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='clothingtype',
            name='type_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип одежды'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=100, verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='display_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код цвета'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_family',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Категория цвета'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='color',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='clothing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.clothingtype', verbose_name='Тип одежды'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расходная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Популярное'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, verbose_name='Новое'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Код модели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по скидке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all', 'All-season')], default='all', max_length=10, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'В наличии'), ('archived', 'Архивирован'), ('oos', 'Нет в наличии')], default='draft', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='Приоритет показа'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(default='jpg', max_length=20, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Автоматически заполняется после загрузки', max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant', verbose_name='Вариация'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Баркод'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, verbose_name='Мин. в наличии'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по скидке'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='status',
            field=models.CharField(default='Active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='size',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Классификация'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='size',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
    ]
