# Generated by Django 5.0.6 on 2025-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_clothingtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'В наличии'), ('archived', 'Архивирован'), ('oos', 'Нет в наличии')], default='active', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('png', 'png'), ('jpg', 'jpg'), ('jpeg', 'jpeg')], default='png', max_length=20, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'В наличии'), ('archived', 'Архивирован'), ('oos', 'Нет в наличии')], default='active', max_length=12, verbose_name='Статус'),
        ),
    ]
