# Generated by Django 5.0.6 on 2025-10-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_stock_quantity_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Код модели'),
        ),
    ]
