# Generated by Django 5.0.6 on 2025-10-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['product', 'color', 'display_order'], 'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='catalog.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='Порядок показа'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основное фото для этого цвета'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Модель'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product', 'color'), name='one_primary_per_color'),
        ),
    ]
