# Generated by Django 5.0.6 on 2025-10-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_productimage_color_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='weight',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, editable=False, verbose_name='В наличии'),
        ),
    ]
