# Generated by Django 5.0.6 on 2025-10-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_product_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('spring', 'Весная'), ('summer', 'Лето'), ('autumn', 'Осень'), ('winter', 'Зима'), ('all', 'Всесезон')], default='all', max_length=10, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='В наличии'),
        ),
    ]
