# Generated by Django 5.0.6 on 2025-11-04 07:22

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_clean_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Загрузите фото (будет сохранено в Supabase)', null=True, storage=apps.core.storage.SupabaseStorage, upload_to='', verbose_name='Загрузить фото'),
        ),
    ]
