# Generated by Django 5.0.6 on 2025-11-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_populate_category_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
