# Generated by Django 5.0.6 on 2025-11-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_category_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Буквенный код (S, M, L, XL)'),
        ),
    ]
