# Generated by Django 5.0.6 on 2025-12-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_size_size_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Баркод'),
        ),
    ]
