# Generated by Django 5.0.6 on 2025-12-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_barcode_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/banners/', verbose_name='Баннер коллекции'),
        ),
    ]
