# Generated by Django 5.0.6 on 2025-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_change_banner_to_imagefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Уход'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
    ]
