# Generated by Django 5.0.6 on 2025-12-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_care_instructions_product_fabric_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='Supabase video URL', max_length=500, verbose_name='URL видео')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Video thumbnail URL', max_length=500, verbose_name='URL миниатюры')),
                ('display_order', models.IntegerField(default=0, help_text='Order in product gallery (0 = first)', verbose_name='Порядок отображения')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True, verbose_name='Длительность (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Видео товара',
                'verbose_name_plural': 'Видео товаров',
                'db_table': 'product_videos',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
