# Generated by Django 5.0.6 on 2025-12-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_productvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['color', 'display_order', 'created_at'], 'verbose_name': 'Видео товара', 'verbose_name_plural': 'Видео товаров'},
        ),
        migrations.AddField(
            model_name='productvideo',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='catalog.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, WebM)', null=True, upload_to='product_videos/', verbose_name='Файл видео'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Supabase video URL (auto-generated or manual)', max_length=500, verbose_name='URL видео'),
        ),
    ]
