# Generated by Django 5.0.6 on 2025-12-11 12:49

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_productvideo_options_productvideo_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, WebM)', null=True, storage=apps.core.storage.video_storage, upload_to='product_videos/', verbose_name='Файл видео'),
        ),
    ]
