# Generated by Django 5.0.6 on 2025-12-11 14:44

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_productvideo_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, WebM)', null=True, storage=apps.catalog.models.get_video_storage, upload_to='product_videos/', verbose_name='Файл видео'),
        ),
    ]
