# Generated by Django 5.2.5 on 2025-08-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_description_alter_item_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
